"""CombinedGeneratorStage — single LLM call for Analyzer + Generator.

Experimental feature: reduces API calls by 50% by combining the two-stage
Analyzer → Generator pipeline into a single LLM call that outputs WikiPage
directly.

Configuration:
    RUFLO_COMBINED_GENERATION=true   Enable combined generation (default: false)
    RUFLO_SHADOW_MODE=true           Run both paths and compare (default: false)
"""
from __future__ import annotations

import json
import logging
import re
from typing import Any

from ...knowledge.core.object import KnowledgeObject, KnowledgeType, LifecycleState, Provenance
from ...lib.budgeted import BudgetedLLM
from ...wiki.core.types import PageType, WikiPage
from ...wiki.features.tag_namespace import build_tag_prompt_section, TAG_PREFIXES
from ...wiki.core.id_generator import generate_page_id
from ...wiki.templates import render_body, required_slot_names
from .._pipeline_common import parse_llm_json
from .._prompt_common import (
    JSON_FORMAT_RULES,
    LANGUAGE_RULES,
    build_generator_header,
)
from ..ports import PipelineContext, StageResult

_logger = logging.getLogger(__name__)

# Tag namespace rules for prompts
TAG_NAMESPACE_RULES = build_tag_prompt_section()


COMBINED_PROMPT = """{header}

## Context
- Source: {source_path}
- Folder: {folder_context}

## Source text
{source_text}

## Task
Analyze the source text and generate a wiki page directly. Output a JSON object:

{{
  "frontmatter": {{
    "id": "<auto-generated or custom slug>",
    "title": "<page title>",
    "type": "source|entity|concept|synthesis",
    "grade": "A|B|C",
    "processing_depth": "concept|memory",
    "tags": ["前缀/名称", ...]
  }},
  "body": {{
    "summary": "<1-2 sentence summary>",
    "content": "<main content in markdown>",
    "relations": [
      {{"target": "<target slug>", "type": "relates_to|references|...", "context": "..."}}
    ]
  }}
}}

## Page type guidelines
- **source**: Raw document extraction (use for primary sources)
- **entity**: Person, organization, location, etc.
- **concept**: Abstract idea, theory, methodology
- **synthesis**: Synthesized insights from multiple sources

## Tag rules
{tag_rules}
- Prefix must be one of: {tag_prefixes}
- Format: "前缀/名称" (no spaces in name)

## Output rules
{json_rules}
{language_rules}

## Example
Input source: "张三是一名软件工程师，他在北京工作..."

Output:
```json
{{
  "frontmatter": {{
    "id": "zhang-san",
    "title": "张三",
    "type": "entity",
    "grade": "B",
    "processing_depth": "concept",
    "tags": ["角色/人物"]
  }},
  "body": {{
    "summary": "张三是软件工程师，在北京工作。",
    "content": "## 基本信息\\n\\n张三是一名软件工程师，目前在北京工作。\\n\\n## 相关内容\\n\\n...",
    "relations": []
  }}
}}
```
"""


class CombinedGeneratorStage:
    """Single LLM call that produces WikiPage directly."""

    name = "combined_generator"

    async def run(self, ctx: PipelineContext, prev_result) -> StageResult:
        """Generate WikiPage in single LLM call.

        Args:
            ctx: Pipeline context with collector_result
            prev_result: CollectorDonePayload from previous stage

        Returns:
            StageResult with {"pages": [WikiPage], "knowledge_object": KnowledgeObject}
        """
        if ctx.collector_result is None:
            return StageResult(success=False, payload={"error": "missing collector result"})

        source_text = ctx.collector_result.content
        source_path = ctx.source_path or ctx.source

        # Build prompt
        header = build_generator_header()
        prompt = COMBINED_PROMPT.format(
            header=header,
            source_path=source_path,
            folder_context=ctx.folder_context or "",
            source_text=source_text[:50000],  # Truncate to avoid token limits
            tag_rules=TAG_NAMESPACE_RULES,
            tag_prefixes="|".join(TAG_PREFIXES),
            json_rules=JSON_FORMAT_RULES,
            language_rules=LANGUAGE_RULES,
        )

        # Call LLM
        try:
            model = getattr(ctx.provider, 'model', 'default') if ctx.provider else 'default'
            budgeted = BudgetedLLM(model=model, provider=ctx.provider)
            response = await budgeted.call(
                prompt=prompt,
                response_format={"type": "json_object"},
            )

            # Parse response
            result = parse_llm_json(response)

            # Build WikiPage
            page = self._build_page(result, source_path, ctx)

            # Build KnowledgeObject for downstream stages
            ko = self._build_knowledge_object(result, source_path, ctx)

            return StageResult(
                success=True,
                payload={
                    "pages": [page],
                    "knowledge_object": ko,
                }
            )

        except Exception as e:
            _logger.exception("[CombinedGenerator] LLM call failed: %s", e)
            return StageResult(success=False, payload={"error": str(e)})

    def _build_page(self, result: dict, source_path: str, ctx: PipelineContext) -> WikiPage:
        """Build WikiPage from LLM response."""
        frontmatter = result.get("frontmatter", {})
        body_data = result.get("body", {})

        # Determine page type
        type_str = frontmatter.get("type", "entity")
        try:
            page_type = PageType(type_str.lower())
        except ValueError:
            page_type = PageType.ENTITY

        # Generate ID if not provided
        page_id = frontmatter.get("id") or generate_page_id(frontmatter.get("title", "untitled"))

        # Build body markdown
        body = self._build_body(body_data, page_type)

        return WikiPage(
            id=page_id,
            title=frontmatter.get("title", "Untitled"),
            type=page_type,
            sources=[source_path],
            body=body,
            grade=frontmatter.get("grade", "B"),
            processing_depth=frontmatter.get("processing_depth", "concept"),
            tags=frontmatter.get("tags", []),
            relations=self._parse_relations(body_data.get("relations", [])),
        )

    def _build_body(self, body_data: dict, page_type: PageType) -> str:
        """Build body markdown from slots."""
        summary = body_data.get("summary", "")
        content = body_data.get("content", "")

        parts = []
        if summary:
            parts.append(f"## 概要\n\n{summary}\n")
        if content:
            parts.append(content)

        return "\n".join(parts) if parts else ""

    def _parse_relations(self, relations: list) -> list:
        """Parse relations from LLM response."""
        from ...wiki.features.relations import Relation

        result = []
        for r in relations:
            if isinstance(r, dict) and "target" in r:
                result.append(Relation(
                    target_id=r["target"],
                    type=r.get("type", "relates_to"),
                    context=r.get("context", ""),
                ))
        return result

    def _build_knowledge_object(self, result: dict, source_path: str, ctx: PipelineContext) -> KnowledgeObject:
        """Build KnowledgeObject for downstream compatibility."""
        frontmatter = result.get("frontmatter", {})

        # Map page type to knowledge type
        type_str = frontmatter.get("type", "entity")
        knowledge_type = {
            "source": KnowledgeType.DOCUMENT,
            "entity": KnowledgeType.ENTITY,
            "concept": KnowledgeType.CONCEPT,
            "synthesis": KnowledgeType.SYNTHESIS,
        }.get(type_str.lower(), KnowledgeType.ENTITY)

        return KnowledgeObject(
            id=frontmatter.get("id") or generate_page_id(frontmatter.get("title", "untitled")),
            title=frontmatter.get("title", "Untitled"),
            type=knowledge_type,
            content="",
            lifecycle=LifecycleState.PROCESSING,
            confidence=0.7,
            provenance=Provenance(
                source_path=source_path,
                ingested_at=ctx.collector_result.extracted_at if ctx.collector_result else 0,
            ),
        )
