"""Auto-generated by scripts/sync_wiki_spec.py. Do not edit manually."""

ID_RULES = {
    "pattern": "^(?:card_[0-9a-f]{13}_[0-9a-f]{8}_[a-z0-9-]+|[a-z0-9-]+)$",
    "max_length": 64,
    "reserved": ['index', 'log'],
}

FRONTMATTER_RULES = {
    "required": ['id', 'title', 'type'],
    "optional": ['sources', 'relations', 'grade', 'processing_depth', 'is_immutable', 'heat', 'last_used_at', 'zombie_since', 'tags'],
}

BODY_RULES = {
    "min_length": 1,
    "max_length": 50000,
    "wikilink_syntax": "[[slug]]",
    "allowed_markdown": ['bold', 'italic', 'headings', 'lists', 'wikilinks'],
}

WIKI_RULES_SUMMARY = '''
# Wiki 规范

## ID 命名规则

ID 有两种可用格式：

- kebab-case slug：如 `shuang-dian`、`ceo-romance`
- UUID v7 (`card_<13hex>_<8hex>_<slug>`)：如 `card_018f3a8e2b1c4_a3f9d12c_lin-feng`，v2.2+ 默认生成

审计工具（H4）同意两种格式；不得使用 `index`、`log` 等保留 ID。

## Frontmatter 字段

### 必须字段

| 字段 | 类型 | 说明 |
|---|---|---|
| `id` | str | 与文件名一致，不含 `.md` |
| `title` | str | 显示标题 |
| `type` | PageType | `source` \\| `entity` \\| `concept` \\| `synthesis` |

### 可选字段

`sources`、`relations`、`grade`、`processing_depth`、`is_immutable`、`heat`、`last_used_at`、`zombie_since`、`tags`

### Tags 规则

Tags 使用受控命名空间前缀，格式为 `prefix/name`。可用前缀：

| 前缀 | 说明 |
|---|---|
| `genre/` | 题材类型 |
| `func/` | 功能类型 |
| `char/` | 角色类型 |
| `event/` | 事件类型 |
| `mood/` | 情绪氛围 |
| `entity/` | 是什么 (What) |
| `scene_phase/` | 何时用 (When) |
| `status/` | 生命周期 |

## Body 规则

- 不得为空（空 body → LINT-EMPTY-BODY INFO 告警）
- 支持 Markdown：`**bold**`、`*italic*`、`## 标题`、`### 子标题`、`- 列表`
- 跨页引用使用 `[[slug]]` 语法，如 `[[shuang-dian]]`
'''
