"""End-to-end smoke test for the ingest path.

Exercises the full chain:

    POST /api/v1/projects/{id}/ingest
      → services.ingest.enqueue_source
      → queue.enqueue_task (queues + triggers _process_next)
      → event_bus.emit("collector:start", …)
      → pipeline._dispatch_collector_start (registered via fix/server)
      → collector.collect  (file read directly from raw/sources/<file>)
      → pipeline._on_collector_done
      → pipeline.run_ingest  (analyze → generate → atomic write)
      → WikiPages written under <project>/wiki/{sources,entities,…}/
      → index.md + log.md updated

After the 2026-07 Inbox cleanup the collector no longer writes a staged
copy to ``Inbox/Processing/<task_id>.md`` and the pipeline no longer
moves the source file on success. The source stays at
``<project>/raw/sources/<file>`` and the wiki page's ``sources:`` field
references that user-visible path.

This is the ONLY test that catches regressions in the WIRING between
modules. Each of fix/server, fix/permissions, fix/pipeline, fix/llm has
its own unit-level regression test, but none of them verify that POST
actually produces a wiki page end to end.

LLM stages are stubbed at pipeline.analyze / pipeline.generate (no real
Ollama / OpenAI call). The test is hermetic and runs in <2s.
"""
import time

import pytest

from src.wiki.core.types import PageType, WikiPage
from src.wiki.storage.page_writer import read_page


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def fresh_project(tmp_path, monkeypatch):
    """Init a fresh wiki project at tmp_path/e2e and register it globally.

    Yields the ProjectContext so the test can read its id + path.
    """
    project_root = tmp_path / "e2e"
    project_root.mkdir()

    # Redirect the GlobalRegistryStore so the project is discoverable by id.
    from src.project import paths as project_paths
    monkeypatch.setattr(project_paths, "_OVERRIDE_CONFIG_DIR", tmp_path)

    from src.project.context import ProjectContext
    ctx = ProjectContext.from_path(project_root, name="e2e")
    return ctx


@pytest.fixture
def stub_llm_pipeline(monkeypatch):
    """Stub pipeline.analyze and pipeline.generate so the test does not
    need a real LLM. Returns the canned WikiPage that ``generate`` will
    produce so the test can assert against it."""
    from src.pipeline import pipeline as pipeline_module

    # Force legacy mode — the new candidate path (default) bypasses the
    # monkeypatched analyze/generate and would need a real LLM provider.
    monkeypatch.setenv("RUFLO_PIPELINE_MODE", "legacy")

    canned_page = WikiPage(
        id="card_e2e_smoke_001",
        title="E2E Smoke Test",
        type=PageType.SOURCE,
        sources=["raw/sources/sample.md"],
        body="# E2E Smoke\n\nThis page was generated by the e2e test.",
        created_at=1700000000000,
        updated_at=1700000000000,
        grade="B",
        processing_depth="concept",
        heat=50,
    )

    async def fake_analyze(*args, **kwargs):
        from src.pipeline.schemas import AnalysisResult
        return AnalysisResult(
            task_id=kwargs.get("task_id", "test"),
            source_path=kwargs.get("source_path", ""),
            summary="e2e smoke",
            key_facts=["stub fact"],
            entities=[],
            concepts=[],
            suggested_pages=[],
            links_to_existing=[],
            folder_context=kwargs.get("folder_context", ""),
        )

    async def fake_generate(*args, **kwargs):
        return [canned_page]

    monkeypatch.setattr(pipeline_module, "analyze", fake_analyze)
    monkeypatch.setattr(pipeline_module, "generate", fake_generate)
    monkeypatch.setattr(pipeline_module, "_get_provider", lambda **kw: None)

    # Stub permission check so the project-relative path resolves cleanly
    # under the tmp_path monkeypatch (which is the project root).
    from src.pipeline import collector as collector_module
    monkeypatch.setattr(
        collector_module, "enforce_permission",
        lambda *a, **kw: None,
    )
    import src.permissions as permissions_module
    monkeypatch.setattr(
        permissions_module, "enforce_permission",
        lambda *a, **kw: None,
    )

    return canned_page


@pytest.fixture
def reset_queue(monkeypatch):
    """Reset the queue and circuit breaker between tests so each starts clean."""
    from src.circuit_breaker import CircuitState
    from src.queue import __reset_for_testing, get_default_queue_service
    from src.queue.retry import MAX_RETRIES

    __reset_for_testing()
    service = get_default_queue_service()
    service.pause()
    cb = service._breaker()
    cb._state = CircuitState.CLOSED
    cb._failure_count = 0
    service.resume()
    yield


# ---------------------------------------------------------------------------
# The smoke test itself
# ---------------------------------------------------------------------------


def test_post_ingest_produces_wiki_page_end_to_end(
    fresh_project, stub_llm_pipeline, reset_queue, tmp_path
):
    """Full chain: init project → write raw doc → POST → drive queue →
    assert wiki page + index + log + source-stays-in-place all happen."""
    from fastapi.testclient import TestClient

    from src.server.app import create_app
    from src.queue import get_default_queue_service, get_queue
    from src.types import KnowledgeTask

    # --- Arrange --------------------------------------------------------
    project_root = fresh_project.path
    raw_dir = project_root / "raw" / "sources"
    raw_dir.mkdir(parents=True, exist_ok=True)
    raw_file = raw_dir / "sample.md"
    raw_file.write_text(
        "# Sample\n\nThis is a raw source document for the e2e smoke test.\n",
        encoding="utf-8",
    )

    # CWD-anchor: the project's ingest service normalises paths against
    # project_root; the collector then resolves ``raw/sources/sample.md``
    # to the absolute path under project_root.
    monkeypatch_cwd = pytest.MonkeyPatch()
    monkeypatch_cwd.chdir(project_root)

    try:
        app = create_app()
        client = TestClient(app)

        # --- Act: POST the ingest --------------------------------------
        resp = client.post(
            f"/api/v1/projects/{fresh_project.id}/ingest",
            json={"source": "raw/sources/sample.md"},
        )
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert body["status"] == "queued", body
        task_id = body["taskId"]
        assert task_id, "POST should return a taskId"

        # --- Act: drive the queue --------------------------------------
        service = get_default_queue_service()
        service.advance(prefer_task_id=task_id, project_id=fresh_project.id)

        deadline = time.time() + 10
        while time.time() < deadline:
            current = next(
                (t for t in get_queue() if t.id == task_id), None
            )
            if current and current.status.value in ("approved", "failed", "dead_letter"):
                break
            time.sleep(0.1)

        # --- Assert: wiki page was written -----------------------------
        wiki_sources = project_root / "wiki" / "sources"
        page_path = wiki_sources / "card_e2e_smoke_001.md"
        assert page_path.exists(), (
            f"Wiki page not written at {page_path}. "
            "Either fix/server (handler not registered), fix/permissions "
            "(raw/sources denied), fix/pipeline (collector didn't run), "
            "or fix/llm (wrong provider selected) is broken end-to-end."
        )

        page = read_page(wiki_sources / "card_e2e_smoke_001.md")
        assert page.id == "card_e2e_smoke_001"
        assert page.title == "E2E Smoke Test"
        assert page.type == PageType.SOURCE
        assert "stub" in page.body or "smoke" in page.body.lower()

        # --- Assert: index.md contains the page ------------------------
        index_md = (project_root / "wiki" / "index.md").read_text(
            encoding="utf-8"
        )
        assert "card_e2e_smoke_001" in index_md

        # --- Assert: log.md contains the ingest event ------------------
        log_md = (project_root / "wiki" / "log.md").read_text(
            encoding="utf-8"
        )
        assert task_id in log_md
        assert "ingest" in log_md.lower()

        # --- Assert: queue reached APPROVED ----------------------------
        current = next(t for t in get_queue() if t.id == task_id)
        assert current.status.value == "approved", (
            f"task final status {current.status.value!r}: {current.error!r}"
        )

        # --- Assert: 2026-07 cleanup contract — source stays put ------
        # The collector no longer moves the source file to Inbox/Processing;
        # the original artefact must still exist at its user-visible path
        # after a successful ingest.
        assert raw_file.exists(), (
            f"Source file at {raw_file} was moved or deleted by the pipeline. "
            "After the 2026-07 cleanup, the source file must remain at "
            "its original location. Re-ingestion dedup is handled by the "
            "md5 cache in src/utils/idempotency.py."
        )

        # No Inbox/ subdir should exist anywhere in the project.
        for inbox_dir in project_root.glob("**/Inbox"):
            assert not any(inbox_dir.glob("Processing")), (
                f"Inbox/Processing/ should not exist under {inbox_dir} after "
                "the 2026-07 cleanup."
            )

    finally:
        monkeypatch_cwd.undo()