"""End-to-end smoke test for the ingest path.

Exercises the full chain:

    POST /api/v1/projects/{id}/ingest
      → services.ingest.enqueue_source
      → queue.enqueue_task (queues + triggers _process_next)
      → event_bus.emit("collector:start", …)
      → pipeline._dispatch_collector_start (registered via fix/server)
      → collector.collect  (file read + staged copy under processing_path)
      → pipeline._on_collector_done
      → pipeline.run_ingest  (analyze → generate → atomic write)
      → WikiPages written under <project>/wiki/{sources,entities,…}/
      → index.md + log.md updated
      → post-success move of source to Inbox/Processing (fix/pipeline)

This is the ONLY test that catches regressions in the WIRING between
modules. Each of fix/server, fix/permissions, fix/pipeline, fix/llm has
its own unit-level regression test, but none of them verify that POST
actually produces a wiki page end to end.

LLM stages are stubbed at pipeline.analyze / pipeline.generate (no real
Ollama / OpenAI call). The test is hermetic and runs in <2s.
"""
import asyncio
import time
from pathlib import Path

import pytest

from src.wiki.core.types import PageType, WikiPage
from src.wiki.storage.page_writer import read_page


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def fresh_project(tmp_path, monkeypatch):
    """Init a fresh wiki project at tmp_path/e2e and register it globally.

    Yields the ProjectContext so the test can read its id + path.
    """
    project_root = tmp_path / "e2e"
    project_root.mkdir()

    # Redirect the GlobalRegistryStore so the project is discoverable by id.
    # config_dir() reads _OVERRIDE_CONFIG_DIR (a module-level sentinel) when
    # set; monkeypatching the *function* wouldn't help because the store
    # captures paths.registry_path at class-definition time.
    from src.project import paths as project_paths
    monkeypatch.setattr(project_paths, "_OVERRIDE_CONFIG_DIR", tmp_path)

    from src.project.context import ProjectContext
    ctx = ProjectContext.from_path(project_root, name="e2e")
    return ctx


@pytest.fixture
def stub_llm_pipeline(monkeypatch):
    """Stub pipeline.analyze and pipeline.generate so the test does not
    need a real LLM. Returns the canned WikiPage that ``generate`` will
    produce so the test can assert against it."""
    from src.pipeline import pipeline as pipeline_module

    canned_page = WikiPage(
        id="card_e2e_smoke_001",
        title="E2E Smoke Test",
        type=PageType.SOURCE,
        sources=["raw/sources/sample.md"],
        body="# E2E Smoke\n\nThis page was generated by the e2e test.",
        created_at=1700000000000,
        updated_at=1700000000000,
        grade="B",
        processing_depth="concept",
        heat=50,
    )

    async def fake_analyze(*args, **kwargs):
        # AnalysisResult is a dataclass. The stub generate below ignores
        # analysis output, but fake_analyze still returns a shape-correct
        # instance so any incidental inspection doesn't crash.
        from src.pipeline.schemas import AnalysisResult
        return AnalysisResult(
            task_id=kwargs.get("task_id", "test"),
            source_path=kwargs.get("source_path", ""),
            summary="e2e smoke",
            key_facts=["stub fact"],
            entities=[],
            concepts=[],
            suggested_pages=[],
            links_to_existing=[],
            folder_context=kwargs.get("folder_context", ""),
        )

    async def fake_generate(*args, **kwargs):
        return [canned_page]

    monkeypatch.setattr(pipeline_module, "analyze", fake_analyze)
    monkeypatch.setattr(pipeline_module, "generate", fake_generate)

    # Also stub _get_provider so the pipeline never tries to instantiate a
    # real LLM provider when run_ingest threads one through (it does pass
    # ``provider=`` even though analyze/generate ignore it).
    monkeypatch.setattr(
        pipeline_module, "_get_provider", lambda: None,
    )

    # Stub collector's permission check on the staged raw_path. The test
    # uses an absolute path under tmp_path/Inbox/Processing (from the stub
    # InboxManager), which the PurePosixPath is_relative_to check rejects
    # against the relative "Inbox/Processing" boundary. The permission
    # check is structurally redundant here because the InboxManager owns
    # the path; stubbing it is acceptable for this e2e smoke test.
    #
    # collector.py imports enforce_permission at module load time
    # (`from ..permissions import …`), so we must patch the already-bound
    # name in the collector module. pipeline.py does the import inline
    # inside _on_collector_done, so it picks up any later patch on
    # src.permissions.enforce_permission.
    from src.pipeline import collector as collector_module
    monkeypatch.setattr(
        collector_module, "enforce_permission",
        lambda *a, **kw: None,
    )
    import src.permissions as permissions_module
    monkeypatch.setattr(
        permissions_module, "enforce_permission",
        lambda *a, **kw: None,
    )

    return canned_page


@pytest.fixture
def reset_queue(monkeypatch):
    """Reset the queue and circuit breaker between tests so each starts clean."""
    from src.circuit_breaker import CircuitState
    from src.queue import queue as queue_module

    queue_module.__reset_for_testing()
    queue_module.pause_queue()
    cb = queue_module.get_circuit_breaker(queue_module.CIRCUIT_BREAKER_NAME)
    cb._state = CircuitState.CLOSED
    cb._failure_count = 0
    queue_module.resume_queue()
    yield


@pytest.fixture
def stub_inbox_in_tmp(tmp_path, monkeypatch):
    """Point the global InboxManager at tmp_path/Inbox so the staged copy
    under processing_path lands in tmp_path and not the host's real Inbox."""
    from src.inbox import manager as manager_module
    from src.inbox.manager import InboxManager

    inbox = InboxManager(base_path=str(tmp_path / "Inbox"))
    inbox.ensure_dirs()
    monkeypatch.setattr(manager_module, "_inbox_manager", inbox)
    return inbox


# ---------------------------------------------------------------------------
# The smoke test itself
# ---------------------------------------------------------------------------


def test_post_ingest_produces_wiki_page_end_to_end(
    fresh_project, stub_llm_pipeline, reset_queue, stub_inbox_in_tmp, tmp_path
):
    """Full chain: init project → write raw doc → POST → drive queue →
    assert wiki page + index + log + post-success move all happen."""
    from fastapi.testclient import TestClient

    from src.server.app import create_app
    from src.queue import queue as queue_module

    # --- Arrange --------------------------------------------------------
    project_root = fresh_project.path
    raw_dir = project_root / "raw" / "sources"
    raw_dir.mkdir(parents=True, exist_ok=True)
    raw_file = raw_dir / "sample.md"
    raw_file.write_text(
        "# Sample\n\nThis is a raw source document for the e2e smoke test.\n",
        encoding="utf-8",
    )

    # Use a path relative to CWD (server's expected form for permission check).
    # Project root IS the CWD-like anchor — pass the raw/sources relative form.
    cwd_anchor = project_root
    monkeypatch_cwd = pytest.MonkeyPatch()
    monkeypatch_cwd.chdir(cwd_anchor)

    try:
        app = create_app()
        client = TestClient(app)

        # --- Act: POST the ingest --------------------------------------
        resp = client.post(
            f"/api/v1/projects/{fresh_project.id}/ingest",
            json={"source": "raw/sources/sample.md"},
        )
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert body["status"] == "queued", body
        task_id = body["taskId"]
        assert task_id, "POST should return a taskId"

        # --- Act: drive the queue --------------------------------------
        # _process_next emits collector:start; _dispatch_collector_start
        # uses asyncio.run since no loop is running in this sync test.
        queue_module._process_next(task_id, fresh_project.id)

        # Poll for terminal state (Fix 3: success moves source; failure keeps it).
        deadline = time.time() + 10
        while time.time() < deadline:
            current = next(
                (t for t in queue_module._queue if t.id == task_id), None
            )
            if current and current.status.value in ("approved", "failed", "dead_letter"):
                break
            time.sleep(0.1)

        # --- Assert: wiki page was written -----------------------------
        wiki_sources = project_root / "wiki" / "sources"
        page_path = wiki_sources / "card_e2e_smoke_001.md"
        assert page_path.exists(), (
            f"Wiki page not written at {page_path}. "
            "Either fix/server (handler not registered), fix/permissions "
            "(raw/sources denied), fix/pipeline (move ran before LLM), "
            "or fix/llm (wrong provider selected) is broken end-to-end."
        )

        page = read_page(wiki_sources / "card_e2e_smoke_001.md")
        assert page.id == "card_e2e_smoke_001"
        assert page.title == "E2E Smoke Test"
        assert page.type == PageType.SOURCE
        assert "stub" in page.body or "smoke" in page.body.lower()

        # --- Assert: index.md contains the page ------------------------
        index_md = (project_root / "wiki" / "index.md").read_text(
            encoding="utf-8"
        )
        assert "card_e2e_smoke_001" in index_md

        # --- Assert: log.md contains the ingest event ------------------
        log_md = (project_root / "wiki" / "log.md").read_text(
            encoding="utf-8"
        )
        assert task_id in log_md
        assert "ingest" in log_md.lower()

        # --- Assert: queue reached APPROVED ----------------------------
        current = next(t for t in queue_module._queue if t.id == task_id)
        assert current.status.value == "approved", (
            f"task final status {current.status.value!r}: {current.error!r}"
        )

        # --- Assert: Fix 3 contract — source moved to Processing ------
        # Only the staged Inbox/Processing copy under tmp_path is checked;
        # the project_root/raw/sources/sample.md still exists because we
        # POSTed the CWD-relative path "raw/sources/sample.md", which the
        # collector resolves against tmp_path/e2e/. The staged task_id copy
        # under stub_inbox_in_tmp.processing_path MUST exist.
        staged = stub_inbox_in_tmp.processing_path / f"{task_id}.md"
        assert staged.exists(), (
            f"Staged copy at {staged} missing — safe_write did not run."
        )

        # The source's project-relative form must have been moved to the
        # stub inbox's processing_path by the post-success handler (Fix 3).
        moved_to_processing = stub_inbox_in_tmp.processing_path / "sample.md"
        assert moved_to_processing.exists(), (
            "Fix 3 contract: source must be moved to Inbox/Processing "
            f"after run_ingest succeeds. Expected {moved_to_processing}."
        )

    finally:
        monkeypatch_cwd.undo()