#!/usr/bin/env python3
"""Install git hooks for this repository.

Creates .git/hooks/pre-commit that runs:
1. AGENTS.md / CLAUDE.md body-sync check (P2-A: dual-file hashing)
2. scripts/sync_wiki_spec.py
Idempotent: safe to run multiple times.
"""
import sys
from pathlib import Path

HOOK_CONTENT = """#!/usr/bin/env python
# Auto-generated by scripts/setup_git_hooks.py
# Do not edit manually
import hashlib
import subprocess
import sys
from pathlib import Path

cwd = "{repo_root}"

# Check 1: AGENTS.md / CLAUDE.md 正文同步校验（跳过前 3 行：标题/空行/工具名）
agents = Path(cwd) / "AGENTS.md"
claude = Path(cwd) / "CLAUDE.md"
if agents.exists() and claude.exists():
    a_lines = agents.read_bytes().split(b"\\n")
    c_lines = claude.read_bytes().split(b"\\n")
    if len(a_lines) >= 4 and len(c_lines) >= 4:
        a_body = b"\\n".join(a_lines[3:])
        c_body = b"\\n".join(c_lines[3:])
        if a_body != c_body:
            print("ERROR: AGENTS.md and CLAUDE.md body content differs — "
                  "update both files before commit")
            sys.exit(1)

# Check 2: wiki-spec.md 同步
sys.path.insert(0, "{repo_root}")
result = subprocess.run([sys.executable, "{sync_script}"], cwd="{repo_root}")
sys.exit(result.returncode)
"""


def render_hook(repo_root: Path) -> str:
    repo_root = repo_root.resolve()
    return HOOK_CONTENT.format(
        repo_root=str(repo_root).replace("\\", "/"),
        sync_script=str(repo_root / "scripts" / "sync_wiki_spec.py").replace("\\", "/"),
    )


def install(repo_root: Path, hooks_dir: Path | None = None) -> Path:
    """Install the local hook into an explicit repository hooks directory."""
    repo_root = repo_root.resolve()
    hooks_dir = (hooks_dir or repo_root / ".git" / "hooks").resolve()
    hook_path = hooks_dir / "pre-commit"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path.write_text(render_hook(repo_root), encoding="utf-8")
    hook_path.chmod(0o755)
    return hook_path


def main() -> int:
    repo_root = Path(__file__).parent.parent.resolve()
    hook_path = install(repo_root)
    print(f"Installed pre-commit hook: {hook_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
