#!/usr/bin/env python3
"""Install git hooks for this repository.

Creates .git/hooks/pre-commit that runs:
1. AGENTS.md / CLAUDE.md body-sync check (P2-A: dual-file hashing)
2. scripts/sync_wiki_spec.py
Idempotent: safe to run multiple times.
"""
from pathlib import Path
import sys

HOOK_CONTENT = """#!/usr/bin/env python
# Auto-generated by scripts/setup_git_hooks.py
# Do not edit manually
import hashlib
import subprocess
import sys
from pathlib import Path

cwd = "{cwd}"

# Check 1: AGENTS.md / CLAUDE.md 正文同步校验（跳过前 3 行：标题/空行/工具名）
agents = Path(cwd) / "AGENTS.md"
claude = Path(cwd) / "CLAUDE.md"
if agents.exists() and claude.exists():
    a_lines = agents.read_bytes().split(b"\\n")
    c_lines = claude.read_bytes().split(b"\\n")
    if len(a_lines) >= 4 and len(c_lines) >= 4:
        a_body = b"\\n".join(a_lines[3:])
        c_body = b"\\n".join(c_lines[3:])
        if a_body != c_body:
            print("ERROR: AGENTS.md and CLAUDE.md body content differs — "
                  "update both files before commit")
            sys.exit(1)

# Check 2: wiki-spec.md 同步
sys.path.insert(0, "{cwd}")
sys.path.insert(0, "{repo_root}")
result = subprocess.run([sys.executable, "{sync_script}"], cwd="{cwd}")
sys.exit(result.returncode)
"""

REPO_ROOT = Path(__file__).parent.parent.resolve()
SYNC_SCRIPT = REPO_ROOT / "scripts" / "sync_wiki_spec.py"
CWD = REPO_ROOT
HOOK_PATH = REPO_ROOT / ".git" / "hooks" / "pre-commit"


def main() -> int:
    # Use forward slashes for cross-platform compatibility
    content = HOOK_CONTENT.format(
        cwd=str(CWD).replace("\\", "/"),
        repo_root=str(REPO_ROOT).replace("\\", "/"),
        sync_script=str(SYNC_SCRIPT).replace("\\", "/"),
    )
    HOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    HOOK_PATH.write_text(content, encoding="utf-8")
    HOOK_PATH.chmod(0o755)
    print(f"Installed pre-commit hook: {HOOK_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
