#!/usr/bin/env python3
"""Install git hooks for this repository.

Creates .git/hooks/pre-commit that runs scripts/sync_wiki_spec.py.
Idempotent: safe to run multiple times.
"""
from pathlib import Path
import sys

HOOK_CONTENT = """#!/usr/bin/env python
# Auto-generated by scripts/setup_git_hooks.py
# Do not edit manually
import subprocess
import sys
sys.path.insert(0, "{cwd}")
sys.path.insert(0, "{repo_root}")
result = subprocess.run([sys.executable, "{sync_script}"], cwd="{cwd}")
sys.exit(result.returncode)
"""

REPO_ROOT = Path(__file__).parent.parent.resolve()
SYNC_SCRIPT = REPO_ROOT / "scripts" / "sync_wiki_spec.py"
CWD = REPO_ROOT
HOOK_PATH = REPO_ROOT / ".git" / "hooks" / "pre-commit"


def main() -> int:
    # Use forward slashes for cross-platform compatibility
    content = HOOK_CONTENT.format(
        cwd=str(CWD).replace("\\", "/"),
        repo_root=str(REPO_ROOT).replace("\\", "/"),
        sync_script=str(SYNC_SCRIPT).replace("\\", "/"),
    )
    HOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    HOOK_PATH.write_text(content, encoding="utf-8")
    HOOK_PATH.chmod(0o755)
    print(f"Installed pre-commit hook: {HOOK_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
