#!/usr/bin/env python3
"""Sync wiki-spec.md → src/pipeline/wiki_rules_prompt.py

Run via pre-commit hook. Compares MD5 of docs/guides/wiki-spec.md against
.wiki-spec-md5; if unchanged, exits 0 silently. If changed, regenerates
wiki_rules_prompt.py and updates the MD5 record.
"""
import hashlib
import sys
from pathlib import Path

import yaml

SPEC_PATH = Path("docs/guides/wiki-spec.md")
OUTPUT_PATH = Path("src/pipeline/wiki_rules_prompt.py")
MD5_PATH = Path(".wiki-spec-md5")


def _read_md5_record() -> str:
    return MD5_PATH.read_text().strip() if MD5_PATH.exists() else ""


def _write_md5_record(md5: str) -> None:
    MD5_PATH.write_text(md5 + "\n")


def _compute_md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def _parse_frontmatter(spec_text: str) -> dict:
    parts = spec_text.split("---", 2)
    fm = parts[1]
    return yaml.safe_load(fm)


def _parse_body(spec_text: str) -> str:
    """Extract Markdown body (everything after the second ---)."""
    parts = spec_text.split("---", 2)
    return parts[2].strip() if len(parts) > 2 else ""


def _generate_prompt_module(data: dict, body_text: str = "") -> str:
    rules = data["rules"]
    id_rules = rules["id"]
    fm_rules = rules["frontmatter"]
    body_rules = rules["body"]

    lines: list[str] = []
    lines.append('"""Auto-generated by scripts/sync_wiki_spec.py. Do not edit manually."""')
    lines.append("")

    # ID_RULES
    lines.append("ID_RULES = {")
    lines.append(f'    "pattern": "{id_rules["pattern"]}",')
    lines.append(f'    "max_length": {id_rules["max_length"]},')
    lines.append(f'    "reserved": {id_rules["reserved"]},')
    lines.append("}")
    lines.append("")

    # FRONTMATTER_RULES
    lines.append("FRONTMATTER_RULES = {")
    lines.append(f'    "required": {fm_rules["required"]},')
    lines.append(f'    "optional": {fm_rules["optional"]},')
    lines.append("}")
    lines.append("")

    # BODY_RULES — all keys from body_rules in spec
    lines.append("BODY_RULES = {")
    for key, value in body_rules.items():
        if isinstance(value, str):
            lines.append(f'    "{key}": "{value}",')
        elif isinstance(value, list):
            lines.append(f'    "{key}": {value},')
        else:
            lines.append(f'    "{key}": {value},')
    lines.append("}")
    lines.append("")

    # WIKI_RULES_SUMMARY — driven entirely by the spec's Markdown body
    escaped_body = body_text.replace("\\", "\\\\")
    lines.append("WIKI_RULES_SUMMARY = '''")
    lines.append(escaped_body)
    lines.append("'''")

    return "\n".join(lines) + "\n"


def main() -> int:
    if not SPEC_PATH.exists():
        print(f"WARN: {SPEC_PATH} not found, skipping sync", file=sys.stderr)
        return 0

    current_md5 = _compute_md5(SPEC_PATH)
    last_md5 = _read_md5_record()

    if current_md5 == last_md5:
        return 0  # No change, nothing to do

    spec_text = SPEC_PATH.read_text(encoding="utf-8")
    data = _parse_frontmatter(spec_text)
    body_text = _parse_body(spec_text)
    content = _generate_prompt_module(data, body_text)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH}")

    _write_md5_record(current_md5)

    return 0


if __name__ == "__main__":
    sys.exit(main())
